FROM ubuntu:18.04

RUN apt-get update
ENV TZ=America/Rochester
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 php libapache2-mod-php git openssl
RUN useradd -ms /bin/bash alice
RUN echo "alice:Password123!" | chpasswd
RUN adduser alice sudo
RUN git clone https://github.com/Nathan-CSEC731/Lab5.git ./webshell
RUN mv ./webshell/* /var/www/html

RUN sed -i "s/Options Indexes FollowSymLinks/Options FollowSymLinks/" /etc/apache2/apache2.conf
RUN sed -i "s/ServerSignature Off/ServerTokens Prod/" /etc/apache2/apache2.conf

COPY ./apache-selfsigned.key /etc/ssl/private/apache-selfsigned.ke
COPY ./apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt
COPY ./ssl-params.conf /etc/apache2/conf-available/ssl-params.conf
COPY ./default-ssl.conf /etc/apache2/sites-available/default-ssl.conf


COPY ./startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/startup.sh

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/user/local/bin/startup.sh"]
